// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMTbj3qSMJqql3_9YxifPmymKa1mAGQRw',
    appId: '1:929444955347:web:d3ee37d2aeaa2c967f0026',
    messagingSenderId: '929444955347',
    projectId: 'money-mouthy-fb',
    authDomain: 'money-mouthy-fb.firebaseapp.com',
    storageBucket: 'money-mouthy-fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALhiH9No-1eyjyf4L9Rwi--ztrU7tzLsY',
    appId: '1:929444955347:android:a8d2475569df1f807f0026',
    messagingSenderId: '929444955347',
    projectId: 'money-mouthy-fb',
    storageBucket: 'money-mouthy-fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxN6KL34PBaKSgPJMaSWTg8ELyFlAb0qE',
    appId: '1:929444955347:ios:194d5f4fee0b58647f0026',
    messagingSenderId: '929444955347',
    projectId: 'money-mouthy-fb',
    storageBucket: 'money-mouthy-fb.firebasestorage.app',
    iosBundleId: 'com.example.moneyMouthyTwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxN6KL34PBaKSgPJMaSWTg8ELyFlAb0qE',
    appId: '1:929444955347:ios:194d5f4fee0b58647f0026',
    messagingSenderId: '929444955347',
    projectId: 'money-mouthy-fb',
    storageBucket: 'money-mouthy-fb.firebasestorage.app',
    iosBundleId: 'com.example.moneyMouthyTwo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMTbj3qSMJqql3_9YxifPmymKa1mAGQRw',
    appId: '1:929444955347:web:e52e2a470e2082287f0026',
    messagingSenderId: '929444955347',
    projectId: 'money-mouthy-fb',
    authDomain: 'money-mouthy-fb.firebaseapp.com',
    storageBucket: 'money-mouthy-fb.firebasestorage.app',
  );
}
